### ISSUE TITLE
make different folders for various similar notes

### ISSUE THREAD

**Issue by ankita132** [ankita132/notes_app#9]

**Comment by Shashwat-Garg** [comment]
What exactly do you mean by 'similar notes' here ?
Similar as in 'for the same user' or 'as per genre' ?

**Comment by ankita132** [comment]
'as per genre'

**Comment by spattk** [comment]
What will be the advantage of it .
Can you please site some examples for it on how it should work. Some reference sort of things .

**Comment by ankita132** [comment]
as in I want that if we have a number of notes then if we have them sorted as per genre we can keep track of similar notes

**Comment by prabhakarpd7284** [comment]
For this feature, what we can do is 
Make a 'genre' column in 'notes' table.
On adding and editing notes, a dropdown menu can show the list of available genres to select from it or the user can add another genre in this list.

**Comment by prabhakarpd7284** [comment]
@ankita132 , please comment on the above approach.

**Comment by ankita132** [comment]
seems quite a good idea. Please proceed with this idea.
